import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { AuthProvider } from '../components/AuthProvider';
import { Sidebar } from '../components/Sidebar';
import { Widgets } from '@/components/Widgets';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AuthProvider>
          <main className='flex min-h-screen mx-auto container  p-4'>
            <Sidebar/>
            {children}
            <Widgets/>
            
            </main>
        </AuthProvider>
      </body>
    </html>
  );
}
